README.md
Added instructions for first launch of binary on Windows - restic install will fail and close the process if backrest.exe is not launched as administrator the first time.
=> docs: update README.md covering first time windows usage instructions 

internal/auth/middleware.go
Added a simple check for HTTP Basic authorization. Seems to work fine with Authentik SSO passing the auth header.
This does not add `WWW-Authenticate` header since it normally expects to receive Bearer auth for JWT.
I am not familiar with go, so I presume that `bcrypt.CompareHashAndPassword` takes care of timing attacks and I don't have to add `ConstantTimeCompare` myself. Please correct me if I am wrong.
Maybe adding rate limiting for brute force detection would be a good idea. Should it be added only for Basic auth, or is it relevant for Bearer token as well?
=> feat: check for basic auth (#110)

Dockerfile.alpine
Alpine is very much up to date with rclone. Using their provided rclone will probably be more stable due for lack of library and dependency issues.
=> fix: install rclone with apk for alpine image

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, .vscode/launch.json, .vscode/tasks.json, CONTRIBUTING.md
I added VSCode Dev Container configuration, which adds effortless dev environment setup for those who use VSCode and Docker.
It includes VSCode launch configurations for backend and frontend.
From what I tested, all the core dependencies are installed during creation of the container, and npm packages are installed when launching project.
Maybe it could be improved slightly to wait for backend to start before starting frontend, but as I see it, it is not that important.
Here is a short video on how I start it in a few minutes.
[Screencast from 2024-02-24 03-33-37.webm](https://github.com/garethgeorge/backrest/assets/1036439/f1ac73f9-1047-4265-aa66-6baf36f30075)
I tested only on Linux but it should work on Windows and MacOS as well, of course it starts it in a Linux container. Still, I …
=> chore: add devcontainer and vscode launch configurations

install.sh
Apple usually puts a quarantine flag on downloaded binaries, that are not signed. This prevents execution of the file. This PR adds a command to the `install.sh` file, to automatically remove the quarantine flag of the installed binary.
*tested on macOS 14.x*
=> feat: automatically remove Apples quarantine flag

webui/src/views/AddRepoModal.tsx, webui/src/views/GettingStartedGuide.tsx
Some docs links already did this, this makes the rest of them match.
I was worried when I clicked on one of the links in a form tooltip and the page navigated away that I might've lost what I'd typed in.
=> Open docs links in a new tab

internal/resticinstaller/resticinstaller.go
Fixes #199.
restic only builds for 386 and amd64. Windows ARM supports emulated amd64 binaries, so download that.
=> feat: use amd64 restic for arm64 Windows

.github/workflows/release.yml, .goreleaser.yaml
I took a stab at #193. It seems to work. You need a PAT with repo permissions, and a repository that starts with `homebrew-` (e.g. `homebrew-backrest-tap`.) That's pretty much it.
You can see the formula it created here: https://github.com/johnmaguire/homebrew-backrest-tap
You can install it with `brew install johnmaguire/backrest-tap/backrest`. To enable the service, run `brew service start backrest`. I tried running the service as root, but got the following error, and I'm out of time to look at this for now:
```
panic: couldn't determine home directory: $HOME is not defined
goroutine 1 [running]:
github.com/garethgeorge/backrest/internal/config.getHomeDir()
/home/runner/work/backrest/backrest/internal/config/environment.go:80 +0x68 …
```
=> Add homebrew support

scripts/get.sh
This Bash script include those feature:
1. Install / Update / Uninstall Backrest
2. Start / Stop / Check Status of Backrest
When it install Backrest it will check CPU/Kernel tpye ( x86_64, Armv6, Arm64), if not those type it should stop the install process.
After check CPU/Kernel tpye, it will use `wget` to download the correct version of Backrest install pack from newest release. Then create a folder/path name "backrest" under `/home/username`, then unpackage the install pack the install pack and run installer.sh inside it, after that it will clean the install file (remove the `/home/username/backrest`).
Uninstall feature is same as install but excute the `uninstall.sh` script.
other feature use `sudo systemctl` command to manage it.
Which plateform this script should support:
Linux …
=> feat: add a Bash script to help Linux user manage Backrest

internal/resticinstaller/resticinstaller.go
While working on #201, I noticed that this code returned `C:\Program Files (x86)` on 64-bit systems, and `C:\Program Files` on 32-bit systems. However, the code downloads a 64-bit binary on 64-bit machines, so it should go in `C:\Program Files` also.
This PR doesn't try to clean up the old file, in case it is in use by another script on the system.
I do wonder if `C:\Program Files\restic` is the best place to install it - were restic to create an installer, it's plausible they would use that as their own install directory. It may be a little safer for backrest to install it into its own program directory, or perhaps some kind of %AppData% directory. 🤷
=> fix: use C:\Program Files\backrest on both x64 and 32-bit

install.sh
When backrest is already installed, and the script is used for updating (as with #187), the install might fail:
If backrest is already running, the cp in the install script fails with "Text file is busy". If the service is already existing, maybe containing customized configuration, it is overwritten. This PR fixes both.
Check if the systemd service is already running, and stop it before installing. Do not overwrite the existing backrest service file.
=>  fix: Linux ./install.sh script fails when used for updating backrest 

pkg/restic/outputs.go, pkg/restic/restic_test.go
I am a happy user of backrest on a legacy device (NAS QNAP TS-219P).
Restic and back-rest are working fabulously: I manage to convince non CLI-savy member of my family to switch to restic thanks to that UI.
Also, is blazing fast comparing to the official backup UI solutions proposed by QNAP.
However, to make it work I had to patch the output parsing function to avoid overflows in integer variables.
The minor memory and performance overhead of using 64bit vars on 32bit system are unnoticeable, even in my quite low-specs device (512M ram, single-core 1.2GHz arm v5l cpu).
```
fix: use explicity int64 for 32bit compat
For the int type the compiler defaults to int32 on 32bit systems, causing backrest to fail when unmarshaling large number from json.
Here we explictly changed all the int …
```
=> fix: use int64 for large values in structs for compatibility with 32bit devices

install.sh
In attempting to upgrade to 0.17.2 on MacOS, I noticed errors when running install.sh. It appears that the changes in be09303 broke the Darwin install. I restore the `install_unix()` function, which had be renamed, to contain the common code, and left the Linux-specific code in `install_or_update_unix()`. 
I haven't tested on Linux, but the change is small enough that I think I haven't broken anything.
=> fix: install.sh was calling systemctl on Darwin

README.md
Just updating the readme to show 'macOS' instead of 'MacOS.'
macOS is the current name.  Previously, was Mac OS X and before that, Mac OS.
=> docs: replace 'MacOS' to 'macOS' in README.md

docs/content/3.cookbooks/2.reverse-proxy-examples.md
Hey Folks!
I was planning to build an app like this over the long weekend and was pleasantly surprised to find one already exists! I’d love to contribute in any way possible.
I use Caddy as a reverse proxy to front Backrest. I've included a basic example to demonstrate how to front Backrest with Caddy. This setup can be expanded to allow Caddy to auto-generate SSL certificates using the ACME client and to bind to authentication sources like Google via oAuth. This approach simplifies the dev work on Backrest by eliminating the need to implement authentication against Google and other login methods.  I can certainly write that up next!
Thanks for taking this PR into consideration!
=> docs: cookbook example for proxying backrest with caddy

CONTRIBUTING.md, README.md, docs/content/0.index.md
Very tiny tweaks to docs.  Added new Markdown Alerts syntax that looks like this for callouts:
=> docs: spring cleaning with minor doc tweaks

.github/workflows/docs.yml
This should add a broken link detection step to the docs deployment workflow.  In the background, it's really using [Muffet](https://github.com/raviqqe/muffet) and doing this:
```
muffet -v --max-connections=3 --timeout=20 --buffer-size=8192 --color=always --exclude="(/_nuxt/|discord.com)" https://garethgeorge.github.io/backrest/
```
**Why add this?**
Doc sites are always important to the end user and the devs.  Broken links help no one and can happen out-of-the-blue.  Checking all links during the build would be beneficial as we could fix broken links before users notice them.
**Notes**
* Later on down the road, we may want to have this check be a separate GH Action that runs nightly.
* In this workflow, we're deploying the pages first and then scanning the public endpoint for broken …
=> ci(docs): Added broken link detection to docs deploy workflow

docs/content/3.cookbooks/1.command-hook-examples.md
Fix typo of "contorl" to "control"
=> docs: fix typo in command hook cookbook 

internal/orchestrator/tasks/hookvars.go
Hi,
I noticed that in hooks .EventName with SNAPSHOT_SUCCESS was reported as unkown
It is a little fix
P.S.: Just noticed it closes #390
=> fix: add condition_snapshot_success to .EventName

cmd/backrest/backrest.go, go.mod, go.sum, internal/hook/hook.go, internal/metric/metric.go, internal/orchestrator/orchestrator.go, internal/orchestrator/tasks/task.go, internal/orchestrator/tasks/taskbackup.go, internal/orchestrator/tasks/taskcheck.go, internal/orchestrator/tasks/taskcollectgarbage.go, internal/orchestrator/tasks/taskforget.go, internal/orchestrator/tasks/taskforgetsnapshot.go, internal/orchestrator/tasks/taskindexsnapshots.go, internal/orchestrator/tasks/taskprune.go, internal/orchestrator/tasks/taskrestore.go, internal/orchestrator/tasks/taskstats.go
Note: this is a first pass at supporting prometheus metrics. 
Reserving the right to rename / change the schema of / add or remove metrics in a followup version but including these as they are for initial feedback.
Note: /metrics is an authenticated endpoint, you must either disable authentication or send requests with basic auth to scrape it.
=> feat: add prometheus metrics

docs/content/2.docs/1.operations.md
=> docs: correct minor spelling and grammar errors

cmd/backrest/backrest.go, internal/oplog/sqlitestore/sqlitestore.go
See https://github.com/garethgeorge/backrest/pull/499 for context on how this performs under benchmarks.
tl;dr is that this offers better performance for common operations and is more robust storage.
=> feat: migrate oplog history from bbolt to sqlite store

internal/orchestrator/tasks/taskcollectgarbage.go
Garbage collection now enforces limits that better guarantee correctness w.r.t. new scheduling features (e.g. last run relative scheduling) and that make more sense in the UI.
For each repo 
* Prune and Check operations retain the last 12 executions. More than this should not be necessary. They are retained for a maximum time of 12 months.
* Stats operations are retained for up to 1 year OR 100 data points to preserve preformance.
* All other operations are retained up to 30 days or 100 operations.
Note that "snapshot" association overrides these rules e.g. if an operation is associated with a snapshot that is still present in the repo, the operation will not be deleted until that snapshot is forgotten.
=> fix: garbage collection with more sensible limits grouped by plan/repo

build/windows/install.nsi
Various fixes before decisions are made regarding multi-purpose installer (https://github.com/garethgeorge/backrest/issues/549)
1. Changed installation location to user %localappdata%\programs since the installer already installed all icons and made registry entry only for the current user.
2. Fixed blurry installer text on high DPI screens.
3. Fixed icon for Start Menu, Desktop shortcuts, and Add/Remove programs entry.
4. Fixed uninstaller not terminating running application and not fully cleaning up installed files.
Users upgrading from the previous installer should uninstall it first to avoid conflicts. User configuration will stay intact.
=> fix: improve windows installer and relocate backrest on Windows to %localappdata%\programs 

build/windows/install.nsi
* Refactored the code, removed unused parts, added comments.
* In-place upgrade support:
- Added a check for the old installer in order to ensure a smooth upgrade.
- Improved the command for stopping Backrest process.
- Installer now stops Backrest process before the upgrade.
* Switched to LZMA compression, reducing installer size by ~25%.
* Made desktop and startup shortcuts optional.
* Added information about UI port to help prevent conflicts in multi-user concurrent scenario.
* Installer detects BACKREST_PORT env variable and will create/update shortcuts with the custom port.
Known issue:
The old uninstaller doesn't remove everything in C:\Program Files\Backrest. The new installer cleans up unneeded shortcuts and registry entries but cannot remove anything in Program Files since it …
=> fix: substantially improve windows installer experience

README.md
Apologies if I caused confusion around the port behaviour. Running the installer as you described with PowerShell would have the installer pick up the session variable and use the port for UI shortcuts, but Backrest itself would still listen on the default port upon the next reboot.
Also, using : instead of 127.0.0.1: would cause Backrest to listen on all interfaces, thus exposing it to outside access.
The correct way to define a user variable persistently is described in this commit. I also made changes to the installer, including the language around the port. If Backrest supported port definition through a command-line switch (like --port=), then I could add an option to the installer to take user input and create the startup shortcut with the switch. The switch would have to be …
=> Clarify notes about the port for Windows installation

build/windows/install.nsi
* Installer is now versioned - both file name and UI.
* Downgrade is now possible without having to uninstall and install from scratch.
* Clearly indicate whether it is an upgrade, reinstall, or downgrade.
* Remember components page selection from previous installation and honour user deselection of previously selected items.
* Disable installation folder selection for upgrade/reinstall/downgrade scenarios.
* Instead of scaring users with the port information, check listening ports and present the relevant information in case of a conflict.
* Refuse installation with conflicting port, which would result in a non-functioning application anyway.
* Removed PowerShell dependency by switching to native commands.
* Fixed the process termination function where it would not terminate the main …
=> feat: cont'd windows installer refinements

internal/orchestrator/orchestrator.go
Here is an example of `/metrics`
=> Add metric when task fails

webui/src/components/HooksFormList.tsx
fixes: #612 
The Ant Design System Form.Item rules has behavior (bug?) where it requires a TLD to be preset in order for a URL to be valid, which is undesirable for Healthchecks as it allows self hosting an instance, and using a URL like `http://healthchecks:8080` is a valid URL 
I went ahead and removed the rule from both Slack and Discord for consistency, however the TLD check there is less problematic as these are SASS services. I am happy to restore those if it is preferred to continue to have the rule applied to these hooks.
=> fix: avoid ant design url rule as it requires a tld to be present

.goreleaser.yaml
An issue has been identified where Go binaries running on macOS 15 (Sequoia) fail to access local network devices (like rest-server repos) when the binary lacks a LC_UUID load command. This affects backrest when running as a service through Homebrew, while direct Terminal execution works due to inherited permissions.
- Issue tracked in golang/go#68678
- Affects binaries missing LC_UUID (verifiable via `dwarfdump --uuid backrest`)
- Connected to issue #494
- Will be fixed by default in Go 1.24, but requires manual flag for Go 1.23
This PR implements the workaround for Go 1.23 by adding the following linker flag to the release pipeline: `
-ldflags="-B gobuildid"`
Local testing with the modified build flag confirms:
- UUID is properly generated in the binary
- Successfully connects to …
=> fix: local network access on macOS 15 Sequoia

.devcontainer/devcontainer.json
This pull request includes an update to the `.devcontainer/devcontainer.json` file. The change updates the Go version used in the development container configuration. Go 1.23 is needed for some of the dependencies used by this project.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L9-R9): Updated the `VARIANT` argument from `1-1.21-bookworm` to `1-1.23-bookworm` to use a newer version of Go.
=> chore: update devcontainer image

internal/metric/metric.go
This PR changes the metrics type to reflect the actual state of the tasks
This is linked to https://github.com/garethgeorge/backrest/issues/420#issuecomment-2586489675
here is an example of the new metrics output
```
backrest_backup_bytes_added{plan_id="testplan",repo_id="test"} 2309
backrest_backup_bytes_processed{plan_id="testplan",repo_id="test"} 11
backrest_backup_file_warnings{plan_id="testplan",repo_id="test"} 0
backrest_tasks_duration_secs{plan_id="_unassociated_",repo_id="_unassociated_",task_type="collect_garbage"} 0.002664103
backrest_tasks_duration_secs{plan_id="testplan",repo_id="test",task_type="backup"} 1.632216997
backrest_tasks_duration_secs{plan_id="testplan",repo_id="test",task_type="hook"} 0.002073014
backrest_tasks_run_total{plan_id="_unassociated_",repo_id="_unassociat …
```
=> fix: convert prometheus metrics to use `gauge` type

.goreleaser.yaml, go.mod
In PR https://github.com/garethgeorge/backrest/pull/630 a build flag was introduced to generate a LC_UUID for binaries fixing an issue with local network communication on MacOS 15. With Go 1.24 this build flag is not necessary anymore.
- Old PR: https://github.com/garethgeorge/backrest/pull/630, refer to its "Note"
- Go 1.24 changelog on that issue: https://tip.golang.org/doc/go1.24#linker
Upgrade Go version and remove deprecated flag.
Local build of Backrest now contains UUID without needing the flag.
=> chore: update Go version and remove workaround

.devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml, .gitignore, .vscode/launch.json, .vscode/tasks.json
This addresses some problems that I had trying to get backrest running with VS Code Dev Containers:
* Some npm dependencies were causing issues, regrettably I don't have logs to share details but since you have a lockfile available I am doing the install with `pnpm` (via `npx`) instead of `npm`
* The backrest.go file had moved
* The dev container was not building the backend since it still used go 1.23
* In a search for all 1.23 I updated the github workflows to go 1.24 as well, can remove those edits if not desireable
It may also be helpful to note somewhere the most recently used versions for go packages since mismatched versions make for excess changes (particularly since the generated files all include the version number of the generator). For my other pull request I rolled back two …
=> chore: contributor tooling fixes

docs/content/3.cookbooks/1.command-hook-examples.md
The [ToolTipIcon](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.tooltipicon) information enum is "Info" rather than "Information"
=> Fix ToolTipIcon Info Enum

README.md
Just a small documentation change to the README to give an example on how to persist the rclone configuration when using Docker
=> docs: add rclone mount to docker-compose example

README.md
Hi,
the backrest logo is barely visible on GitHub in dark mode, so I adjusted the README to show the logo based on the browser theme.
Updated logo display in README for dark and light themes.
=> Improve logo visibility in dark mode
